name: Docker Image Build and Test 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t qemu_linux .

      - name: Start QEMU and Redirect Output
        run: docker run -d --rm --name qemu_container qemu_linux qemu-system-x86_64 -kernel /boot/vmlinuz -nographic -append "root=/dev/sda init=/bin/busybox sh -c 'ls /' > output.txt"

      - name: Wait for QEMU to Finish
        run: sleep 10

      - name: Display Output
        run: cat output.txt
